FROM node:18-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy project files and environment variables
COPY . .
COPY .env .env

# Expose the Vite dev server port
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
